### ISSUE TITLE
Small issue with the documentation example

### ISSUE THREAD

**Issue by sajirdalas** [endlesshack/youtube-video#1]
On the README example the sources of the videos are saved on variables on <i>webmUrl</i> and <i>mp4Url</i> and tested as the src attribute of a video tag. But <i>webmUrl</i> and <i>mp4Url</i> returns objects, with <i>webmUrl.url</i> and <i>mp4Url.url</i> actually returning the source url string.

It is a small issue, but worth nothing. Confused me for a second when I was trying out the library.

**Comment by jwagener** [comment]
thx. fixed
